require('custom-env').env('dev')

import dotenv from 'dotenv'

dotenv.config()

/** export env constant */
export const env = {
    MONGO_URL: process.env.MONGO_URL,
    JWT_SECRET: process.env.JWT_SECRET,
    TOKEN_SECRET: process.env.TOKEN_SECRET,
    TOKEN_HEADER_KEY: process.env.TOKEN_HEADER_KEY,
    DB_HOST: process.env.DB_HOST,
    DB_USER: process.env.DB_USER,
    DB_PASS: process.env.DB_PASS,
    DB_NAME: process.env.DB_NAME,
    DIALECT: process.env.DIALECT,
    POOL_MAX: process.env.POOL_MAX,
    POOL_MIN: process.env.POOL_MIN,
    POOL_ACQUIRE: process.env.POOL_ACQUIRE,
    POOL_IDLE: process.env.POOL_IDLE,
    APPPORT: process.env.PORT,
    JWT_TIMEOUT_DURATION: process.env.JWT_TIMEOUT_DURATION,
    JWT_TIMEOUT_DURATION_APP: process.env.JWT_TIMEOUT_DURATION_APP,
    JWT_TIMEOUT_DURATION_WEB: process.env.JWT_TIMEOUT_DURATION_WEB,
    LOG_LEVEL:process.env.LOG_LEVEL,
    HOST:process.env.HOST,
    NODE_ENV:process.env.NODE_ENV,
    FCM_SERVER_KEY:process.env.FCM_SERVER_KEY,
    SITE_TITLE:process.env.SITE_TITLE,
    AWS_ACCESS_KEY_ID:process.env.AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY:process.env.AWS_SECRET_ACCESS_KEY,
    AWS_BUCKET_NAME:process.env.AWS_BUCKET_NAME,
    FIREBASE_DOMAIN_PREFIX:process.env.FIREBASE_DOMAIN_PREFIX,
    FIREBASE_LINK:process.env.FIREBASE_LINK,
    ANDROID_PACKAGE:process.env.ANDROID_PACKAGE,
    EMAIL_HOST: process.env.EMAIL_HOST,
    EMAIL_USERNAME: process.env.EMAIL_USERNAME,
    EMAIL_PASSWORD: process.env.EMAIL_PASSWORD,
    TOKEN_SECRET_IN_DAYS: process.env.TOKEN_SECRET_IN_DAYS,
    SITE_URL: process.env.SITE_URL,
    IVR_FLOW_FILE_PATH: process.env.IVR_FLOW_FILE_PATH,
    CRM_RECORDING_URL: process.env.CRM_RECORDING_URL,
    KOMM_RECORDING_URL: process.env.KOMM_RECORDING_URL,
    IN_BACKDAYS: process.env.IN_BACKDAYS,
    NODE_ENV_LOG: process.env.NODE_ENV_LOG,
    NODE_ENV_ERROR_LOG: process.env.NODE_ENV_ERROR_LOG,
    RELEASE_VERSION: process.env.RELEASE_VERSION,
    BUILD_NUMBER: process.env.BUILD_NUMBER,
    REVENUE_PROCESS: process.env.REVENUE_PROCESS,
    CHECK_AGENT_HANG_PROCESS: process.env.CHECK_AGENT_HANG_PROCESS,
    FIREBASE_NOTIFICATION_PROCESS: process.env.FIREBASE_NOTIFICATION_PROCESS,
    TYPE: process.env.TYPE,
    PROJECT_ID: process.env.PROJECT_ID,
    PRIVATE_KEY_ID: process.env.PRIVATE_KEY_ID,
    PRIVATE_KEY: process.env.PRIVATE_KEY,
    CLIENT_EMAIL: process.env.CLIENT_EMAIL,
    CLIENT_ID: process.env.CLIENT_ID,
    AUTH_URI: process.env.AUTH_URI,
    TOKEN_URI: process.env.TOKEN_URI,
    AUTH_PROVIDER_X509_CERT_URI: process.env.AUTH_PROVIDER_X509_CERT_URI,
    CLIENT_X509_CERT_URL: process.env.CLIENT_X509_CERT_URL,
    RAZORPAY_KEY_ID: process.env.RAZORPAY_KEY_ID,
    RAZORPAY_KEY_SECRET: process.env.RAZORPAY_KEY_SECRET,
    CHECK_LIVE_CALL_HANG_PROCESS: process.env.CHECK_LIVE_CALL_HANG_PROCESS,
    log_level: process.env.log_level,
    log_file_size : process.env.log_file_size,
    log_write_to_console_flag : process.env.log_write_to_console_flag,
    log_general_log_path : process.env.log_general_log_path,
    log_general_log_file : process.env.log_general_log_file,
    log_summary_log_path : process.env.log_summary_log_path,
    log_summary_log_file : process.env.log_summary_log_file,
    log_error_log_path : process.env.log_error_log_path,
    log_error_log_file:process.env.log_error_log_file,
    log_cdr_log_path :process.env.log_cdr_log_path,
    log_cdr_log_file : process.env.log_cdr_log_file,
    ADD_TOTAL_LEAD_SUMMARY: process.env.ADD_TOTAL_LEAD_SUMMARY,
    SEND_SMS_END_CALL_URL: process.env.SEND_SMS_END_CALL_URL,
    SEND_SMS_END_CALL_USERNAME: process.env.SEND_SMS_END_CALL_USERNAME,
    SEND_SMS_END_CALL_PASSWORD: process.env.SEND_SMS_END_CALL_PASSWORD,
    READER_DB_HOST: process.env.READER_DB_HOST,
    READER_DB_USER: process.env.READER_DB_USER,
    READER_DB_PASS: process.env.READER_DB_PASS,
    READER_DB_NAME: process.env.READER_DB_NAME,
    WEBRTC_DB_HOST: process.env.WEBRTC_DB_HOST,
    WEBRTC_DB_USER: process.env.WEBRTC_DB_USER,
    WEBRTC_DB_PASS: process.env.WEBRTC_DB_PASS,
    WEBRTC_DB_NAME: process.env.WEBRTC_DB_NAME,
    BIGQUERY_DATABASE_NAME: process.env.BIGQUERY_DATABASE_NAME,
    BIGQUERY_DATA_PROJECTID: process.env.BIGQUERY_DATA_PROJECTID,
    BIGQUERY_DATA_DATASETID: process.env.BIGQUERY_DATA_DATASETID,
    WRINGG_SITE_URL: process.env.WRINGG_SITE_URL,
    CALL_PULSE: process.env.CALL_PULSE,
    EMAIL_FROM: process.env.EMAIL_FROM,
    SITE_ADMIN_URL: process.env.SITE_ADMIN_URL,
    CUSTOM_TOKEN: process.env.CUSTOM_TOKEN,
    PAYMENT_TYPE:process.env.PAYMENT_TYPE
}